
package tedi.tri;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KatalogProdukInterface", targetNamespace = "http://tri.tedi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KatalogProdukInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://tri.tedi/", className = "tedi.tri.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://tri.tedi/", className = "tedi.tri.AddProductResponse")
    @Action(input = "http://tri.tedi/KatalogProdukInterface/addProductRequest", output = "http://tri.tedi/KatalogProdukInterface/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<tedi.tri.Produk>
     */
    @WebMethod
    @WebResult(name = "Produk", targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProductsResponse")
    @Action(input = "http://tri.tedi/KatalogProdukInterface/getProductsRequest", output = "http://tri.tedi/KatalogProdukInterface/getProductsResponse")
    public List<Produk> getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProductResponse")
    @Action(input = "http://tri.tedi/KatalogProdukInterface/getProductRequest", output = "http://tri.tedi/KatalogProdukInterface/getProductResponse")
    public List<String> getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://tri.tedi/", className = "tedi.tri.GetProductCategoriesResponse")
    @Action(input = "http://tri.tedi/KatalogProdukInterface/getProductCategoriesRequest", output = "http://tri.tedi/KatalogProdukInterface/getProductCategoriesResponse")
    public List<String> getProductCategories();

}
